voDescriptorOverwrite:
  catalogue: 9090
  bindingNB:
    ports:
      httpPort: 8080
  databaseConfig:
    timeseriesDB:
      influxDB: disabled

voChartOverwrite:
  serviceAccount:
    create: false
    annotations: {}
    name: "vo"
  ingress:
    enabled: false
  resources:
    limits:
      cpu: "500m"

  autoscaling:
    enabled: false
  serviceImportClusters: []
  clustersAffinity: []

  service:
    type: NodePort
    catalogue:
      nodePort: 30000
    http:
      nodePort: 30001
